[window]
dimensions = { columns = 80, lines = 25 }
position = { x = 349, y = 169 }
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations = "Full"
opacity = 1
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = false
decorations_theme_variant = "Dark"

[scrolling]
history = 10000

[font]
normal = { family = "GeistMono NF", style = "Medium" }
bold = { family = "GeistMono NF", style = "Bold" }
italic = { family = "GeistMono NF", style = "Italic" }
bold_italic = { family = "GeistMono NF", style = "Bold Italic" }
size = 14.0
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors.primary]
background = '#0a0a0a'
foreground = '#f0f0f0'

[colors.cursor]
cursor = '#FFFFFF'
text = '#0a0a0a'

[colors.selection]
text = '#f0f0f0'
background = '#262626'

[colors.normal]
black = '#424242'
red = '#F44747'
green = '#999999'
yellow = '#E2C08D'
blue = '#A9A9A9'
magenta = '#D3D3D3'
cyan = '#DCDCDC'
white = '#D4D4D4'

[colors.bright]
black = '#424242'
red = '#F44747'
green = '#999999'
yellow = '#E2C08D'
blue = '#A9A9A9'
magenta = '#D3D3D3'
cyan = '#DCDCDC'
white = '#D4D4D4'

[bell]
animation = "EaseOut"
duration = 100
color = '#f56464'

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Underline", blinking = "On" }
blink_interval = 550
blink_timeout = 0
unfocused_hollow = false

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login", "-i"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "C", mods = "Alt", action = "Copy" },
    { key = "V", mods = "Alt", action = "Paste" },
    { key = "Plus", mods = "Alt", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Alt", action = "DecreaseFontSize" },
    { key = "0", mods = "Alt", action = "ResetFontSize" },
    { key = "F11", action = "ToggleFullscreen" },
    { key = "M", mods = "Alt", action = "ToggleMaximized" },
    { key = "H", mods = "Alt", action = "Hide" },
    { key = "Q", mods = "Alt", action = "Quit" },
    { key = "PageUp", mods = "Alt", action = "ScrollHalfPageUp" },
    { key = "PageDown", mods = "Alt", action = "ScrollHalfPageDown" },
    { key = "K", mods = "Alt", action = "ScrollLineUp" },
    { key = "J", mods = "Alt", action = "ScrollLineDown" },
    { key = "F", mods = "Alt", action = "SearchForward" },
    { key = "B", mods = "Alt", action = "SearchBackward" },
    { key = "T", mods = "Alt", action = "SpawnNewInstance" },
    { key = "N", mods = "Alt", action = "CreateNewWindow" },
    { key = "E", mods = "Alt", command = { program = "C:\\Users\\arman\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", args = ["."] } },
    { key = "U", mods = "Alt", command = { program = "C:\\Users\\arman\\AppData\\Local\\Programs\\cursor\\Cursor.exe", args = ["."] } },
    { key = "Z", mods = "Alt", command = { program = "C:\\Program Files\\Zen Browser\\zen.exe" } },
    { key = "R", mods = "Alt", command = { program = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" } },
]